parameters:
#    choumei_hello.example.class: Choumei\HelloBundle\Example

services:
#    choumei_hello.example:
#        class: %choumei_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
