<?php

namespace Choumei\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowerRepository extends EntityRepository
{
}