ChoumeiWelcomeBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ChoumeiWelcomeBundle:Default:index }
looks:
    pattern: /looks
    defaults: { _controller: ChoumeiWelcomeBundle:Default:index }

about_us:
    pattern: /about-us
    defaults: { _controller: ChoumeiWelcomeBundle:Default:aboutUs }
business:
    pattern: /business
    defaults: { _controller: ChoumeiWelcomeBundle:Default:business }