ChoumeiWelcomeBundle:
    resource: "@ChoumeiWelcomeBundle/Resources/config/routing.yml"
    prefix:   /

ChoumeiSecurityBundle:
    resource: "@ChoumeiSecurityBundle/Resources/config/routing.yml"
    prefix:   /

ChoumeiHelloBundle:
    resource: "@ChoumeiHelloBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: ChoumeiWelcomeBundle:Default:index }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
