fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile
fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register
fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting
fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /change-password

ChoumeiLooksBundle:
    resource: "@ChoumeiLooksBundle/Controller/"
    type:     annotation
    prefix:   /

ChoumeiWelcomeBundle:
    resource: "@ChoumeiWelcomeBundle/Resources/config/routing.yml"
    prefix:   /

ChoumeiSecurityBundle:
    resource: "@ChoumeiSecurityBundle/Resources/config/routing.yml"
    prefix:   /

ChoumeiHelloBundle:
    resource: "@ChoumeiHelloBundle/Resources/config/routing.yml"
    prefix:   /

ChoumeiSecurityBundle:
    pattern: /admin
    defaults: { _controller: ChoumeiWelcomeBundle:Default:index }
    
_welcome:
    pattern:  /
    defaults: { _controller: ChoumeiWelcomeBundle:Default:index }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
