<?php

namespace Choumei\LooksBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccessoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessoryRepository extends EntityRepository
{
}