<?php

namespace Choumei\LooksBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClothTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClothTypeRepository extends EntityRepository
{
  public function getTypes($parent=NULL){
    $query  = $this->createQueryBuilder('t')
                ->where('t.id = ?', $parent)
                ->orderBy('t.id', 'ASC')
                ->getQuery();
    
    $types  = $query->getResult();            
    return $types;
  }
}