ChoumeiSecurityBundle_follow:
    pattern: /follow/{user_id}
    defaults: { _controller: ChoumeiSecurityBundle:Security:addFollow }
    requirements:
      user_id: \d+
ChoumeiSecurityBundle_new_flower:
    pattern: /latest-flowers
    defaults: { _controller: ChoumeiSecurityBundle:Security:latestFlowers }
choumei_profile_avatar_crop:
    pattern: /avatar/crop
    defaults: { _controller: ChoumeiSecurityBundle:Security:cropAvatar }
choumei_profile_avatar_edit:
    pattern: /avatar/edit
    defaults: { _controller: ChoumeiSecurityBundle:Security:editAvatar }
ChoumeiSecurityBundle_top:
    pattern: /top-users
    defaults: { _controller: ChoumeiSecurityBundle:Security:topUsers }
ChoumeiSecurityBundle_user_edit:
    pattern: /user/edit
    defaults: { _controller: ChoumeiSecurityBundle:Security:editProfile }
    